//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string TotalQty { get; set; }
        public string AvailableQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
